name: Developer Tests

on: push

jobs:
  # Then name of the job is launch-test
  launch-tests:
    runs-on: ubuntu-latest
    # All the steps are executed in the container openjda:8-jdk-alpine
    container: openjdk:8-jdk-alpine

    steps:
      # We checkout the repository's code
      - uses: actions/checkout@v1
      # Instalamos Maven en Alpine
      - name: Install Maven
        run: apk add --no-cache maven
      # Y lanzamos los tests
      - name: Launch tests with Maven
        run: mvn test
